# Generated by Django 3.2.6 on 2021-09-27 17:13

import contribute.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='college_id',
            field=models.ImageField(upload_to=contribute.models.ids_directory_path),
        ),
    ]
