# Generated by Django 3.2.6 on 2021-09-27 17:29

import contribute.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0002_alter_contributor_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='college_id',
            field=models.ImageField(upload_to=contribute.models.ids_directory_path, validators=[contribute.models.validate_image_size]),
        ),
    ]
