# Generated by Django 3.2.6 on 2021-09-15 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('syllabus', models.CharField(max_length=500)),
                ('semester', models.SmallIntegerField()),
                ('credit', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('book', 'Book'), ('video', 'Video Tutorial'), ('web', 'Web Tutorial')], max_length=10)),
                ('author', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('rating', models.SmallIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.subject')),
            ],
        ),
    ]
