# Generated by Django 3.2.6 on 2021-10-06 07:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=resources.models.notes_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'jpg', 'png', 'txt']), resources.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('book', 'Book'), ('video', 'Video Tutorial'), ('web', 'Web Tutorial')], max_length=10)),
                ('link', models.CharField(max_length=500)),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_code', models.CharField(max_length=12)),
                ('department', models.CharField(choices=[('cse', 'Computer Science & engineering'), ('ce', 'Civil engineering'), ('ee', 'Electrical engineering'), ('ece', 'Electronics and communication engineering')], max_length=255)),
                ('semester', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('credit', models.FloatField(verbose_name=django.core.validators.MinValueValidator(1))),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cse', 'Computer Science & engineering'), ('ce', 'Civil engineering'), ('ee', 'Electrical engineering'), ('ece', 'Electronics and communication engineering')], max_length=255)),
                ('semester', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('download_link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'syllabuse',
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('sub_code', 'department'), name='unique_sub_code_per_department'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.subject'),
        ),
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.subject'),
        ),
    ]
