# Generated by Django 3.2.8 on 2021-10-23 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtutorial',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webtutorial',
            name='subject',
            field=models.ForeignKey(db_column='sub_code', on_delete=django.db.models.deletion.CASCADE, to='resources.subject'),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='subject',
            field=models.ForeignKey(db_column='sub_code', on_delete=django.db.models.deletion.CASCADE, to='resources.subject'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(db_column='sub_code', on_delete=django.db.models.deletion.CASCADE, to='resources.subject'),
        ),
        migrations.AddField(
            model_name='taught',
            name='department',
            field=models.ForeignKey(db_column='dept_name', on_delete=django.db.models.deletion.CASCADE, to='resources.department'),
        ),
        migrations.AddField(
            model_name='taught',
            name='subject',
            field=models.ForeignKey(db_column='sub_code', on_delete=django.db.models.deletion.CASCADE, to='resources.subject'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='department',
            field=models.ForeignKey(db_column='dept_name', on_delete=django.db.models.deletion.CASCADE, to='resources.department'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='subject',
            field=models.ForeignKey(db_column='sub_code', on_delete=django.db.models.deletion.CASCADE, to='resources.subject'),
        ),
        migrations.AddField(
            model_name='note',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, to='resources.topic'),
        ),
        migrations.AddField(
            model_name='book',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(db_column='sub_code', on_delete=django.db.models.deletion.CASCADE, to='resources.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='taught',
            unique_together={('subject', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('department', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='questionpaper',
            unique_together={('subject', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('topic', 'contributor')},
        ),
    ]
