# Generated by Django 3.2.6 on 2021-09-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(default='cse', max_length=50),
            preserve_default=False,
        ),
    ]
