# Generated by Django 3.2.6 on 2021-09-21 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210921_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
