# Generated by Django 3.2.6 on 2021-09-22 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cse', 'Computer Science & engineering'), ('ce', 'Civil engineering'), ('ee', 'Electrical engineering'), ('ece', 'Electronics and communication engineering')], max_length=255)),
                ('semester', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('download_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('cse', 'Computer Science & engineering'), ('ce', 'Civil engineering'), ('ee', 'Electrical engineering'), ('ece', 'Electronics and communication engineering')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
