# Generated by Django 3.2.6 on 2021-09-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210922_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name': 'syllabuse'},
        ),
    ]
