# Generated by Django 3.2.6 on 2021-09-22 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_syllabus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_code',
            field=models.SmallIntegerField(default=101, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
