# Generated by Django 3.2.7 on 2021-09-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_subject_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_code',
            field=models.CharField(max_length=10),
        ),
    ]
