# Generated by Django 3.2.7 on 2021-09-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_subject_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_code',
            field=models.CharField(max_length=12),
        ),
    ]
