# Generated by Django 3.2.6 on 2021-09-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_subject_sub_code'),
        ('resources', '0009_note'),
    ]

    operations = [
    ]
