<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-09-24 12:55
=======
# Generated by Django 3.2.6 on 2021-09-24 12:55
>>>>>>> b2f730f9cc939d73823e46342451015431df1ab0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_subject_sub_code'),
        ('resources', '0009_note'),
    ]

    operations = [
    ]
