# Generated by Django 3.2.6 on 2021-09-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_merge_0009_alter_subject_sub_code_0009_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_code',
            field=models.CharField(max_length=10),
        ),
    ]
