# Generated by Django 3.2.6 on 2021-09-24 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_subject_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credit',
            field=models.FloatField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
