# Generated by Django 3.2.6 on 2021-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_alter_subject_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default='introduction to algorithms', max_length=255),
            preserve_default=False,
        ),
    ]
