# Generated by Django 3.2.6 on 2021-09-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_alter_subject_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
