# Generated by Django 3.2.6 on 2021-09-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0001_initial'),
        ('resources', '0015_alter_subject_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribute.contributor'),
        ),
    ]
