# Generated by Django 3.2.6 on 2021-09-27 14:32

import django.core.validators
from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_alter_note_file'),
    ]

