# Generated by Django 3.2.6 on 2021-09-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_auto_20210927_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='author',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
    ]
