# Generated by Django 3.2.6 on 2021-10-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(db_column='dept_name', default='cse', on_delete=django.db.models.deletion.CASCADE, to='resources.department'),
            preserve_default=False,
        ),
    ]
