# Generated by Django 3.2.6 on 2021-09-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('cse', 'Computer Science & engineering'), ('ce', 'Civil engineering'), ('ee', 'Electrical engineering'), ('ece', 'Electronics and communication engineering')], default='cse', max_length=255),
            preserve_default=False,
        ),
    ]
