# Generated by Django 3.2.6 on 2021-09-24 04:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_department'),
    ]
