# Generated by Django 3.2.7 on 2021-09-24 12:56

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_contributor_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='college_id',
            field=models.ImageField(upload_to=users.models.ids_directory_path, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
