# Generated by Django 3.2.6 on 2021-09-26 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_contributor_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
