# Generated by Django 3.2.6 on 2021-09-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_alter_note_uploaded_by'),
        ('users', '0006_alter_user_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
