# Generated by Django 3.2.6 on 2021-09-27 17:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_contributor'),
    ]