# Generated by Django 3.2.6 on 2021-10-06 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211002_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
